/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pemdeskuas;

import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author WINDOWS 11
 */
public class Homepage extends javax.swing.JFrame {

    private String size = "";
    private int selectedRow;

    /**
     * Creates new form Homepage
     */
    private void filter(String query) {
        DefaultTableModel tbl = (DefaultTableModel) tblHasil.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tbl);
        tblHasil.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    public Homepage() {
        initComponents();
        this.pilih();
    }

    class MyList implements ListSelectionListener {

        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;

            }
//            ListSelectionModel lsm = (ListSelectionModel) e.getSource();
//            selectedRow = lsm.getMinSelectionIndex();
//            TableModel tb = tblHasil.getModel();
//            fieldNama.setText(tb.getValueAt(selectedRow, 1).toString());
//            fieldHarga.setText(tb.getValueAt(selectedRow, 2).toString());
//            fieldStok.setText(tb.getValueAt(selectedRow, 3).toString());
//            fieldKode.setEditable(false);
        }
    }

    void pilih() {
        tblHasil.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel rowSM = tblHasil.getSelectionModel();
        rowSM.addListSelectionListener(new MyList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSort = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        fieldHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldStok = new javax.swing.JTextField();
        btnShowAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        checkS = new javax.swing.JCheckBox();
        checkM = new javax.swing.JCheckBox();
        checkL = new javax.swing.JCheckBox();
        checkXL = new javax.swing.JCheckBox();
        checkAll = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSortir = new javax.swing.JButton();
        comboSortCategories = new javax.swing.JComboBox<>();
        comboCategories = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboSize = new javax.swing.JComboBox<>();
        fieldSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        frame2 = new javax.swing.JPanel();
        fieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboSortBy = new javax.swing.JComboBox<>();
        radioAscending = new javax.swing.JRadioButton();
        radioDecrease = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(63, 73, 127));
        jPanel1.setForeground(new java.awt.Color(248, 245, 228));

        jLabel1.setBackground(new java.awt.Color(141, 123, 104));
        jLabel1.setFont(new java.awt.Font("SF UI Display", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventaris B@tiek Solo");

        jLabel13.setBackground(new java.awt.Color(141, 123, 104));
        jLabel13.setFont(new java.awt.Font("SF UI Display", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Welcome!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 20);

        btnUbah.setFont(new java.awt.Font("SF UI Text", 0, 11)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah);
        btnUbah.setBounds(80, 120, 61, 25);

        btnTambah.setFont(new java.awt.Font("SF UI Text", 0, 11)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah);
        btnTambah.setBounds(152, 120, 77, 25);

        btnHapus.setFont(new java.awt.Font("SF UI Text", 0, 11)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(246, 120, 67, 25);

        tblHasil.setFont(new java.awt.Font("SF UI Display", 0, 11)); // NOI18N
        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Size", "Harga", "Sisa Stok"
            }
        ));
        tblHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 340, 810, 260);

        jLabel3.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 90, 60, 16);

        fieldHarga.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(fieldHarga);
        fieldHarga.setBounds(507, 81, 315, 30);

        jLabel4.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sisa Stok");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 40, 60, 16);

        fieldStok.setBackground(new java.awt.Color(217, 217, 217));
        getContentPane().add(fieldStok);
        fieldStok.setBounds(507, 32, 315, 30);

        btnShowAll.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        btnShowAll.setText("Show All");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowAll);
        btnShowAll.setBounds(507, 121, 315, 23);

        jPanel3.setBackground(new java.awt.Color(63, 73, 127));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(440, 30, 400, 130);

        jPanel2.setBackground(new java.awt.Color(63, 73, 127));

        checkS.setBackground(new java.awt.Color(255, 255, 255));
        checkS.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        checkS.setForeground(new java.awt.Color(255, 255, 255));
        checkS.setText("S");
        checkS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSActionPerformed(evt);
            }
        });

        checkM.setBackground(new java.awt.Color(255, 255, 255));
        checkM.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        checkM.setForeground(new java.awt.Color(255, 255, 255));
        checkM.setText("M");
        checkM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMActionPerformed(evt);
            }
        });

        checkL.setBackground(new java.awt.Color(255, 255, 255));
        checkL.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        checkL.setForeground(new java.awt.Color(255, 255, 255));
        checkL.setText("L");

        checkXL.setBackground(new java.awt.Color(255, 255, 255));
        checkXL.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        checkXL.setForeground(new java.awt.Color(255, 255, 255));
        checkXL.setText("XL");

        checkAll.setBackground(new java.awt.Color(255, 255, 255));
        checkAll.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        checkAll.setForeground(new java.awt.Color(255, 255, 255));
        checkAll.setText("All");

        jLabel9.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Size");

        jLabel5.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categories");

        jLabel8.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sortir Barang ");

        btnSortir.setFont(new java.awt.Font("SF Compact Text", 0, 12)); // NOI18N
        btnSortir.setText("Sortir Barang!");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });

        comboSortCategories.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        comboSortCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kemeja", "dress", "tunic" }));
        comboSortCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortCategoriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(checkS)
                            .addGap(0, 0, 0)
                            .addComponent(checkM)
                            .addGap(0, 0, 0)
                            .addComponent(checkL)
                            .addGap(0, 0, 0)
                            .addComponent(checkXL, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3)
                            .addComponent(checkAll, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(comboSortCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboSortCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkS)
                        .addComponent(jLabel9))
                    .addComponent(checkM)
                    .addComponent(checkL)
                    .addComponent(checkXL)
                    .addComponent(checkAll)
                    .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 170, 430, 120);

        comboCategories.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        comboCategories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kemeja", "dress", "tunic" }));
        comboCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriesActionPerformed(evt);
            }
        });
        getContentPane().add(comboCategories);
        comboCategories.setBounds(209, 80, 201, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Category");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(146, 84, 60, 16);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Size");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 84, 70, 16);

        comboSize.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        comboSize.setForeground(new java.awt.Color(217, 217, 217));
        comboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL" }));
        comboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSizeActionPerformed(evt);
            }
        });
        getContentPane().add(comboSize);
        comboSize.setBounds(80, 80, 51, 22);

        fieldSearch.setBackground(new java.awt.Color(217, 217, 217));
        fieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchActionPerformed(evt);
            }
        });
        fieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSearchKeyReleased(evt);
            }
        });
        getContentPane().add(fieldSearch);
        fieldSearch.setBounds(590, 300, 227, 30);

        jLabel11.setFont(new java.awt.Font("SF UI Display", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("Search ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(540, 300, 43, 15);

        frame2.setBackground(new java.awt.Color(63, 73, 127));
        frame2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldNama.setBackground(new java.awt.Color(217, 217, 217));
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        javax.swing.GroupLayout frame2Layout = new javax.swing.GroupLayout(frame2);
        frame2.setLayout(frame2Layout);
        frame2Layout.setHorizontalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frame2Layout.setVerticalGroup(
            frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(frame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(frame2);
        frame2.setBounds(0, 30, 430, 130);

        jLabel12.setFont(new java.awt.Font("SF UI Display", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sort By:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 190, 70, 16);

        comboSortBy.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        comboSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "nama", "size", "harga", "sisa" }));
        comboSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSortByActionPerformed(evt);
            }
        });
        getContentPane().add(comboSortBy);
        comboSortBy.setBounds(510, 180, 315, 30);

        btnGroupSort.add(radioAscending);
        radioAscending.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        radioAscending.setForeground(new java.awt.Color(255, 255, 255));
        radioAscending.setText("Ascending");
        getContentPane().add(radioAscending);
        radioAscending.setBounds(510, 220, 75, 23);

        btnGroupSort.add(radioDecrease);
        radioDecrease.setFont(new java.awt.Font("SF UI Text", 0, 10)); // NOI18N
        radioDecrease.setForeground(new java.awt.Color(255, 255, 255));
        radioDecrease.setText("Decreasing");
        radioDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDecreaseActionPerformed(evt);
            }
        });
        getContentPane().add(radioDecrease);
        radioDecrease.setBounds(590, 220, 77, 23);

        jPanel4.setBackground(new java.awt.Color(63, 73, 127));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(440, 170, 400, 120);

        btnExport.setBackground(new java.awt.Color(63, 73, 127));
        btnExport.setFont(new java.awt.Font("SF UI Display", 1, 11)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export to Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        getContentPane().add(btnExport);
        btnExport.setBounds(690, 610, 132, 25);

        jLabel10.setBackground(new java.awt.Color(248, 245, 228));
        jLabel10.setForeground(new java.awt.Color(248, 245, 228));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/946379_4614.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 840, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            String nama = fieldNama.getText();
            String hargaTxt = fieldHarga.getText();
            Integer harga = Integer.parseInt(hargaTxt);
            String stokTxt = fieldStok.getText();
            Integer stok = Integer.parseInt(stokTxt);
            String kategori = (String) comboCategories.getSelectedItem();
            String sizeUpdate = (String) comboSize.getSelectedItem();
            DBConnect connect = new DBConnect();
            connect.updatePakaian(nama, sizeUpdate, harga, stok, kategori, tblHasil.getValueAt(tblHasil.getSelectedRow(), 0).toString());
            DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
            dtm.setRowCount(0);
            viewDataAll();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            String nama = fieldNama.getText();
            String hargaTxt = fieldHarga.getText();
            Integer harga = Integer.parseInt(hargaTxt);
            String stokTxt = fieldStok.getText();
            Integer stok = Integer.parseInt(stokTxt);
            String kategori = (String) comboCategories.getSelectedItem();
            String sizeTambah = (String) comboSize.getSelectedItem();
            fieldNama.setText("");
            fieldHarga.setText("");
            fieldStok.setText("");

            DBConnect connect = new DBConnect();
            connect.setDataPakaian(nama, sizeTambah, harga, stok, kategori);
            DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
            dtm.setRowCount(0);
            viewDataAll();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
            DBConnect connect = new DBConnect();
            connect.deletePakaian(tblHasil.getValueAt(tblHasil.getSelectedRow(), 0).toString());
            dtm.setRowCount(0);
            viewDataAll();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    final void viewDataAll() {
        DefaultTableModel model = (DefaultTableModel) tblHasil.getModel();
        DBConnect connect = new DBConnect();
        Object[][] data = connect.getDataAll();
        // Hapus semua baris yang ada di model
        model.setRowCount(0);
        System.out.println(connect.getCountAll());
        // Tambahkan baris baru jika model kosong
        if (model.getRowCount() == 0) {
            Object[] row;
            for (int i = 0; i < connect.getCountAll(); i++) {
                row = new Object[]{data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]};
                model.addRow(row);
            }
        }
    }

    final void viewDataPakaian(String categories, String size, String sortBy, boolean isDescending) {
        DefaultTableModel model = (DefaultTableModel) tblHasil.getModel();
        DBConnect connect = new DBConnect();
        Object[][] data = connect.getDataPakaian(categories, size, sortBy, isDescending);
        // Hapus semua baris yang ada di model
        model.setRowCount(0);
        System.out.println(connect.getCountPakaian(categories, size));
        // Tambahkan baris baru jika model kosong
        if (model.getRowCount() == 0) {
            Object[] row;
            for (int i = 0; i < connect.getCountPakaian(categories, size); i++) {
                row = new Object[]{data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]};
                model.addRow(row);
            }
        }
    }

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void tblHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHasilMouseClicked
        // TODO add your handling code here:
        DBConnect connect = new DBConnect();
        fieldNama.setText(tblHasil.getValueAt(tblHasil.getSelectedRow(), 1).toString());
        fieldHarga.setText(tblHasil.getValueAt(tblHasil.getSelectedRow(), 3).toString());
        fieldStok.setText(tblHasil.getValueAt(tblHasil.getSelectedRow(), 4).toString());
        comboCategories.setSelectedItem(connect.getKategori(tblHasil.getValueAt(tblHasil.getSelectedRow(), 0).toString()));
        comboSize.setSelectedItem(connect.getSize(tblHasil.getValueAt(tblHasil.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_tblHasilMouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
        dtm.setRowCount(0);
        viewDataAll();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void comboCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategoriesActionPerformed

    private void comboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSizeActionPerformed

    private void comboSortCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSortCategoriesActionPerformed

    private void fieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchActionPerformed

    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
        dtm.setRowCount(0);
        String categories = (String) comboSortCategories.getSelectedItem();
        String size = "";
        if (checkAll.isSelected()) {
            // Checkbox "checkAll" dicentang, pilih semua ukuran
            size = "";
        } else {
            // Checkbox "checkAll" tidak dicentang, cek masing-masing ukuran
            if (checkS.isSelected()) {
                size += "S,";
            }
            if (checkM.isSelected()) {
                size += "M,";
            }
            if (checkL.isSelected()) {
                size += "L,";
            }
            if (checkXL.isSelected()) {
                size += "XL,";
            }
        }
        // Menghapus koma terakhir jika ada
        if (!size.isEmpty()) {
            size = size.substring(0, size.length() - 1);
        }
        String sortBy = (String) comboSortBy.getSelectedItem();
        boolean isDescending = radioDecrease.isSelected();
        viewDataPakaian(categories, size, sortBy, isDescending);
    }//GEN-LAST:event_btnSortirActionPerformed

    private void checkSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSActionPerformed
        // TODO add your handling code here:
        if (checkS.isSelected()) {
            size += "S"; // Menambahkan "S" ke variabel size jika checkbox S dipilih
        } else {
            size = size.replace("S", ""); // Menghapus "S" dari variabel size jika checkbox S tidak dipilih
        }
    }//GEN-LAST:event_checkSActionPerformed

    private void checkMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMActionPerformed
        // TODO add your handling code here:
        if (checkM.isSelected()) {
            size += "M"; // Menambahkan "M" ke variabel size jika checkbox M dipilih
        } else {
            size = size.replace("M", ""); // Menghapus "M" dari variabel size jika checkbox M tidak dipilih
        }
    }//GEN-LAST:event_checkMActionPerformed

    private void comboSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSortByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSortByActionPerformed

    private void fieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchKeyReleased
        // TODO add your handling code here:
        String query = fieldSearch.getText();
        filter(query);
    }//GEN-LAST:event_fieldSearchKeyReleased

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".xlsx")) {
                filePath += ".xlsx";
            }

            try {
                DefaultTableModel dtm = (DefaultTableModel) tblHasil.getModel();
                Workbook workbook = new XSSFWorkbook();
                Sheet sheet = workbook.createSheet("Data");

                // Menulis header kolom
                Row headerRow = sheet.createRow(0);
                for (int i = 0; i < dtm.getColumnCount(); i++) {
                    Cell cell = headerRow.createCell(i);
                    cell.setCellValue(dtm.getColumnName(i));
                }

                // Menulis data dari tabel
                for (int i = 0; i < dtm.getRowCount(); i++) {
                    Row row = sheet.createRow(i + 1);
                    for (int j = 0; j < dtm.getColumnCount(); j++) {
                        Cell cell = row.createCell(j);
                        cell.setCellValue(String.valueOf(dtm.getValueAt(i, j)));
                    }
                }

                // Menyimpan file
                FileOutputStream fileOut = new FileOutputStream(filePath);
                workbook.write(fileOut);
                fileOut.close();

                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke file Excel!");
                Desktop.getDesktop().open(fileToSave); // Membuka file setelah diekspor
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "File tidak ditemukan: " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void radioDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDecreaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDecreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.ButtonGroup btnGroupSort;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnSortir;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox checkAll;
    private javax.swing.JCheckBox checkL;
    private javax.swing.JCheckBox checkM;
    private javax.swing.JCheckBox checkS;
    private javax.swing.JCheckBox checkXL;
    private javax.swing.JComboBox<String> comboCategories;
    private javax.swing.JComboBox<String> comboSize;
    private javax.swing.JComboBox<String> comboSortBy;
    private javax.swing.JComboBox<String> comboSortCategories;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JTextField fieldStok;
    private javax.swing.JPanel frame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioAscending;
    private javax.swing.JRadioButton radioDecrease;
    private javax.swing.JTable tblHasil;
    // End of variables declaration//GEN-END:variables
}
